# This is a basic workflow to help you get started with Actions

name: deployToAzure
env:
  subscriptionId: c64ca001-2cce-46de-837e-03f5564fc802 # Bakunas Sandbox 2
  azureRegion: East US 2

# Controls when the workflow will run
on:
  # Workflow will run on upon a commit

#  push:
#    branches:
#      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  armDeploy:
    name: Deploy ARM Templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Deploy Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: ${{ env.azureRegion }}
          template: ./AZ-700_Lab-Deploy.json
          parameters: ./AZ-700_Lab-Deploy.parameters.json
          deploymentName: ResourceGroupDeploy-${{ env.networkResourceGroupName }}
